### ISSUE TITLE
vercel部署报错

### ISSUE THREAD

**Issue by Apple-ljj** [deiucanta/chatpad#40]
![微信截图_20230409003833](https://user-images.githubusercontent.com/21351751/230732764-928b9664-29aa-4003-967f-eb85bc22a97b.png)

<html>
<body>

Error: The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.
--
00:36:20.831 | Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
00:36:20.960 | NEXT_NO_ROUTES_MANIFEST: The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.

</body>
</html>

**Comment by Supernova3339** [comment]
the dockerfile doesn't build with the assets installed, you'll need to wait
for a modification

**Comment by darth-pika-hu** [comment]
Same issue here.

**Comment by darth-pika-hu** [comment]
@Apple-ljj @Supernova3339  Add following Environment variable should fix the issue: NODE_VERSION=18

**Comment by theutsavchopra** [comment]
I am facing the same issue with Vercel installation. @Supernova3339 any fix for this?

**Comment by Supernova3339** [comment]
Use the above solution

**Comment by theutsavchopra** [comment]
I tried that still facing that issue. Attached is the screenshot, I have added the environment variable. 
![image_2023-06-01_145329861](https://github.com/deiucanta/chatpad/assets/5067523/f84a0b7b-7a8e-4b71-a1b7-b95e413e4242)

**Comment by theutsavchopra** [comment]
@Supernova3339 awaiting your reply :)
